#################
# Home Assistant#
#################
- id: homeassistant_theme_switch
  alias: Set Home Assistant theme for day and night
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            default
          {% else %}
            midnight
          {% endif %}

###############
# House #
###############

- id: house_start_cleaning
  alias: Start Cleaning
  trigger:
    - entity_id: binary_sensor.someone_home
      for:
        minutes: "10"
      from: "on"
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
  action:
    - data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
      service: vacuum.start

- id: house_stop_cleaning
  alias: Stop Cleaning
  trigger:
    - entity_id: binary_sensor.someone_home
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: template
      value_template: '{{not is_state("vacuum.xiaomi_vacuum_cleaner", "docked")}}'
  action:
    - data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
      service: vacuum.return_to_base

- id: house_alexa_guard_arm
  alias: Alexa Home Guard - Arm
  trigger:
    - entity_id: binary_sensor.someone_home
      from: "on"
      platform: state
      to: "off"
  action:
    - service: alarm_control_panel.alarm_arm_away

- id: house_alexa_guard_disarm
  alias: Alexa Home Guard - Disarm
  trigger:
    - entity_id: binary_sensor.someone_home
      from: "off"
      platform: state
      to: "on"
  action:
    - service: alarm_control_panel.alarm_arm_home

- id: house_sarah_arrive_home
  alias: Sarah comes home
  trigger:
    - entity_id: binary_sensor.hk_presence_sarah
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.hk_presence_bruno
      state: "on"
  action:
    - service: notify.alexa_media
      data:
        data:
          type: announce
        target: media_player.everywhere
        message: Hi Bruno, Sarah will be home in a few minutes

- id: house_bruno_arrive_home
  alias: Bruno comes home
  trigger:
    - entity_id: binary_sensor.hk_presence_bruno
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.hk_presence_sarah
      state: "on"
  action:
    - service: notify.alexa_media
      data:
        data:
          type: announce
        target: media_player.everywhere
        message: Hi Sarah, Bruno will be home in a few minutes

- id: house_all_leave
  alias: Leave House
  trigger:
    - entity_id: binary_sensor.someone_home
      from: "on"
      platform: state
      to: "off"
  action:
    - data:
        entity_id: group.all_lights
      service: light.turn_off
    - data:
        entity_id: group.all_light_switches
      service: switch.turn_off
    - data:
        entity_id: remote.harmony_hub
      service: remote.turn_off

- id: house_sunrise
  alias: Sunrise
  trigger:
    - event: sunrise
      platform: sun
      offset: -00:45:00
  action:
    - data:
        entity_id: input_boolean.dnd_living_room
      service: input_boolean.turn_off
    - data:
        entity_id: input_boolean.dnd_dining_room
    - data:
        entity_id: input_boolean.dnd_master_bedroom
      service: input_boolean.turn_off
    - data:
        entity_id: input_boolean.dnd_emma_bedroom
      service: input_boolean.turn_off
    - data:
        entity_id:
          - media_player.bruno_s_sonos_one
          - media_player.everywhere
          - media_player.emma_s_bedroom_echo_dot
        volume_level: 0.6
      service: media_player.volume_set

- id: house_sunset
  alias: Sunset
  trigger:
    - event: sunset
      platform: sun
      offset: -00:45:00
  condition:
    - condition: state
      entity_id: binary_sensor.someone_home
      state: "on"
  action:
    - data:
        entity_id:
          - switch.balcony_plug
          - switch.dining_room_cabinet
          - switch.emmas_bedroom_string_lights
      service: switch.turn_on
    - data:
        entity_id:
          - light.gaming_area
        brightness: 200
        color_temp: 500
        transition: 30
      service: light.turn_on

- id: house_someone_arrives_after_sunset
  alias: Anyone comes home after Sunset
  trigger:
    - entity_id: binary_sensor.someone_home
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    - data:
        entity_id: automation.sunset
      service: automation.trigger

- id: building_door_bell_ring
  alias: Building Door Bell Ring
  trigger:
    - event_data: {}
      event_type: nello_bell_ring
      platform: event
  condition:
    - condition: state
      entity_id: binary_sensor.someone_home
      state: "on"
  action:
    - data:
        data:
          type: announce
        message: Someone is at the door downstairs
        target: media_player.everywhere
      service: notify.alexa_media

###############
# Living Room #
###############

- id: living_room_watch_tv_lights_on
  alias: Watch TV Lights On
  trigger:
    - entity_id: sensor.watch_netflix
      from: "False"
      platform: state
      to: "True"
    - entity_id: sensor.watch_smart_tv
      from: "False"
      platform: state
      to: "True"
  condition:
    - above: 20
      condition: numeric_state
      entity_id: light.living_room
      value_template: "{{states.light.living_room.attributes.brightness}}"
  action:
    - data:
        brightness: 20
        entity_id: light.living_room
      service: light.turn_on

- id: living_room_watch_tv_lights_off_daytime
  alias: Watch TV Lights Off (Daytime)
  trigger:
    - entity_id: sensor.watch_netflix
      from: "True"
      platform: state
      to: "False"
    - entity_id: sensor.watch_smart_tv
      from: "True"
      platform: state
      to: "False"
  condition:
    condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
    - data:
        entity_id: light.living_room
      service: light.turn_off

- id: living_room_watch_tv_lights_off_nighttime
  alias: Watch TV Lights Off (Nighttime)
  trigger:
    - entity_id: sensor.watch_netflix
      from: "True"
      platform: state
      to: "False"
    - entity_id: sensor.watch_smart_tv
      from: "True"
      platform: state
      to: "False"
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    - data:
        entity_id: light.living_room
        brightness: 100
      service: light.turn_on

- id: living_room_watch_tv_fan_on
  alias: Watch TV Fan On
  trigger:
    - entity_id: sensor.watch_netflix
      from: "False"
      platform: state
      to: "True"
    - entity_id: sensor.watch_smart_tv
      from: "False"
      platform: state
      to: "True"
  condition:
    - above: 25
      condition: numeric_state
      entity_id: sensor.living_room_sensor_temperature
      value_template: "{{states.sensor.living_room_sensor_temperature.state}}"
  action:
    - data:
        command: PowerToggle
        device: "64739991"
        entity_id: remote.harmony_hub
      service: remote.send_command

- id: living_room_watch_tv_fan_off
  alias: Watch TV Fan Off
  trigger:
    - entity_id: sensor.watch_netflix
      from: "True"
      platform: state
      to: "False"
    - entity_id: sensor.watch_smart_tv
      from: "True"
      platform: state
      to: "False"
  action:
    - data:
        command: PowerToggle
        device: "64739991"
        entity_id: remote.harmony_hub
      service: remote.send_command

- id: living_room_watch_tv_dnd_on
  alias: Watch TV DnD On
  trigger:
    - entity_id: sensor.watch_netflix
      from: "False"
      platform: state
      to: "True"
    - entity_id: sensor.watch_smart_tv
      from: "False"
      platform: state
      to: "True"
  action:
    - data:
        entity_id: input_boolean.dnd_living_room
      service: input_boolean.turn_on

- id: living_room_watch_tv_dnd_off
  alias: Watch TV DnD Off
  trigger:
    - entity_id: sensor.watch_netflix
      from: "True"
      platform: state
      to: "False"
    - entity_id: sensor.watch_smart_tv
      from: "True"
      platform: state
      to: "False"
  action:
    - data:
        entity_id: input_boolean.dnd_living_room
      service: input_boolean.turn_off

- id: living_room_motion_start
  alias: Living Room Motion Starts (Motion Toggle Off)
  trigger:
    - entity_id: binary_sensor.living_room_motion_sensor
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: light.living_room
      state: "off"
    - condition: state
      entity_id: input_boolean.motion_living_room
      state: "off"
    - condition: state
      entity_id: input_boolean.dnd_living_room
      state: "off"
  action:
    # Hue bridge not fast enough
    - data_template:
        brightness: "{% if now().hour >= 21 %}100{% elif now().hour < 7 %}50{% else %}250{% endif %}"
        entity_id: light.living_room
      service: light.turn_on
    - data:
        entity_id: input_boolean.motion_living_room
      service: input_boolean.turn_on

- id: living_room_motion_end
  alias: Living Room Motion Ends (Motion Toggle On)
  trigger:
    - entity_id: binary_sensor.living_room_motion_sensor
      from: "on"
      platform: state
      to: "off"
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.motion_living_room
      state: "on"
  action:
    - data:
        entity_id: light.living_room
      service: light.turn_off
    - data:
        entity_id: input_boolean.motion_living_room
      service: input_boolean.turn_off

- id: living_room_motion_toggle_override_off
  alias: Living Room Motion Toggle Override Off
  trigger:
    - entity_id: sensor.living_room_switch
      platform: state
  action:
    - data:
        entity_id: input_boolean.motion_living_room
      service: input_boolean.turn_off

- id: living_room_motion_toggle_override_on
  alias: Living Room Motion Toggle Override On
  trigger:
    - entity_id: light.dining_room
      from: "on"
      platform: state
      to: "off"
  action:
    - data:
        entity_id: input_boolean.motion_living_room
      service: input_boolean.turn_off

###############
# Dining Room #
###############

- id: dining_room_motion_start
  alias: Dining Room Motion Starts (Motion Toggle Off)
  trigger:
    - entity_id: binary_sensor.dining_room_motion_sensor
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: light.dining_room
      state: "off"
    - condition: state
      entity_id: input_boolean.motion_dining_room
      state: "off"
    - condition: state
      entity_id: input_boolean.dnd_dining_room
      state: "off"
  action:
    # Hue bridge not fast enough
    - data_template:
        brightness: "{% if now().hour >= 21 %}100{% elif now().hour < 7 %}50{% else %}250{% endif %}"
        entity_id: light.dining_room
      service: light.turn_on
    - data:
        entity_id: input_boolean.motion_dining_room
      service: input_boolean.turn_on

- id: dining_room_motion_end
  alias: Dining Room Motion Ends (Motion Toggle On)
  trigger:
    - entity_id: binary_sensor.dining_room_motion_sensor
      from: "on"
      platform: state
      to: "off"
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.motion_dining_room
      state: "on"
  action:
    - data:
        entity_id: light.dining_room
      service: light.turn_off
    - data:
        entity_id: input_boolean.motion_dining_room
      service: input_boolean.turn_off

- id: dining_room_motion_toggle_override_off
  alias: Dining Room Motion Toggle Override Off
  trigger:
    - entity_id: sensor.dining_room_switch
      platform: state
    - entity_id: sensor.dining_room_switch_2
      platform: state
    - entity_id: light.dining_room
      from: "on"
      platform: state
      to: "off"
  action:
    - data:
        entity_id: input_boolean.motion_dining_room
      service: input_boolean.turn_off

- id: dining_room_motion_toggle_override_on
  alias: Dining Room Motion Toggle Override On
  trigger:
    - entity_id: light.living_room
      from: "on"
      platform: state
      to: "off"
  action:
    - data:
        entity_id: input_boolean.motion_dining_room
      service: input_boolean.turn_off
