- id: '1566204636758'
  alias: Roomba
  trigger:
  - hours: '15'
    minutes: '00'
    platform: time_pattern
    seconds: '00'
  condition:
  - condition: state
    entity_id: binary_sensor.hk_presence_bruno
    state: 'off'
  - condition: state
    entity_id: binary_sensor.hk_presence_sarah
    state: 'off'
  action:
  - data:
      entity_id: vacuum.roomba
    service: vacuum.turn_on
- id: '1566215577974'
  alias: Alexa Home Guard - Arm
  trigger:
  - entity_id: binary_sensor.hk_presence_bruno
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.hk_presence_sarah
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.hk_presence_bruno
    state: 'off'
  - condition: state
    entity_id: binary_sensor.hk_presence_sarah
    state: 'off'
  action:
  - service: alarm_control_panel.alarm_arm_away
- id: '1566215577979'
  alias: Alexa Home Guard - Disarm
  trigger:
  - entity_id: binary_sensor.hk_presence_bruno
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.hk_presence_sarah
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: alarm_control_panel.alarm_arm_home
- id: '1566215577982'
  alias: Sarah comes home
  trigger:
  - entity_id: binary_sensor.hk_presence_sarah
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.hk_presence_bruno
    state: 'on'
  action:
  - service: notify.alexa_media
    data:
      data:
        type: announce
      target: media_player.everywhere
      message: 'Hi Bruno, Sarah will be home in a few minutes'
- id: '1566215577981'
  alias: Bruno comes home
  trigger:
  - entity_id: binary_sensor.hk_presence_bruno
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.hk_presence_sarah
    state: 'on'
  action:
  - service: notify.alexa_media
    data:
      data:
        type: announce
      target: media_player.everywhere
      message: 'Hi Sarah, Bruno will be home in a few minutes'
- id: '1566416394499'
  alias: Leave House
  trigger:
  - entity_id: binary_sensor.hk_presence_bruno
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.hk_presence_sarah
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.hk_presence_bruno
    state: 'off'
  - condition: state
    entity_id: binary_sensor.hk_presence_sarah
    state: 'off'
  action:
  - data:
      data:
        entity_id: group.all_lights
    service: light.turn_off
  - data:
      data:
        entity_id: group.all_light_switches
    service: switch.turn_off
- id: '1566632827470'
  alias: Sunset
  trigger:
  - event: sunset
    platform: sun
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.hk_presence_bruno
      state: 'on'
    - condition: state
      entity_id: binary_sensor.hk_presence_sarah
      state: 'on'
  action:
  - data:
      data:
        entity_id:
        - switch.balcony_plug
        - switch.dining_room_cabinet
        - switch.emmas_bedroom_string_lights
    service: switch.turn_on
  - data:
      data:
        entity_id:
        - light.gaming_area
        brightness: 200
        color_temp: 500
        transition: 30
    service: light.turn_on
