default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !env_var LATITUDE
  longitude: !env_var LONGITUDE
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 40
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !env_var TIMEZONE

  external_url: "https://lgolhkhmo12h3lgg6cbbnsk0fi929n4i.ui.nabu.casa"

  internal_url: "https://assistant.at.home"

  auth_providers:
    - type: homeassistant

  # Customization file
  customize: !include customize.yaml

  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Lovelace
lovelace:
  mode: yaml
  # Include external resources only add when mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/group-card/group-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity/battery-entity.js
      type: module
    - url: /hacsfiles/zha-network-card/zha-network-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
      type: module
  # Add more dashboards
  dashboards:
    lovelace-overview: # Needs to contain a hyphen (-)
      mode: yaml
      filename: ui-overview.yaml
      title: Overview
      icon: mdi:view-dashboard
      show_in_sidebar: true
      require_admin: false
    lovelace-admin:
      mode: yaml
      title: Admin
      icon: mdi:wrench
      show_in_sidebar: true
      filename: ui-admin.yaml
      require_admin: true

# Recorder
# recorder:
#   purge_keep_days: 5
#   exclude:
#     domains:
#       - automation
#       - weblink
#       - updater
#     entities:
#       - sun.sun
#       - sensor.last_boot
#       - sensor.date

# Enables configuration UI
config:

websocket_api:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include_dir_merge_list automations
scene: !include scenes.yaml
script: !include_dir_merge_named scripts

prometheus:
  namespace: home

system_health:

hacs:
  token: !env_var GITHUB_TOKEN

circadian_lighting:

alexa_media:
  accounts:
    - email: !env_var AMAZON_USER
      password: !env_var AMAZON_PASSWORD
      url: amazon.com
      exclude_devices:
        - "This Device"
        - "Sarah's Alexa Apps"
        - "Bruno's Alexa Apps"
        - "Bruno's Fire TV stick"
        - "Living Room"

airvisual:
  api_key: !env_var AIRVISUAL_API_KEY
