homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !env_var LATITUDE
  longitude: !env_var LONGITUDE
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 40
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !env_var TIMEZONE

  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !env_var HTTP_API_PASSWORD
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 10.0.0.0/8

  # Customization file
  customize: !include customize.yaml

  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: !env_var HTTP_BASE_URL

websocket_api:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

prometheus:
  namespace: home

system_health:

hacs:
  token: !env_var GITHUB_TOKEN

alexa_media:
  accounts:
    - email: !env_var AMAZON_USER
      password: !env_var AMAZON_PASSWORD
      url: amazon.com
      exclude_devices:
      - "This Device"
      - "Sarah's Alexa Apps"
      - "Bruno's Alexa Apps"
      - "Bruno's Fire TV stick"
      - "Living Room"
