title: Admin
preload_cards:
  - custom:layout-card
  - layout-card
  - custom:zha-network-card
  - custom:battery-entity
views:
  - path: default_view
    panel: true
    cards:
      - type: entities
        entities:
          - type: "custom:battery-entity"
            entity: sensor.balcony_door_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.balcony_door_sensor_2_battery
          - type: "custom:battery-entity"
            entity: sensor.bathroom_door_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.front_door_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.closet_door_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.dining_room_wall_switch_battery
          - type: "custom:battery-entity"
            entity: sensor.living_room_wall_switch_battery
          - type: "custom:battery-entity"
            entity: sensor.dining_room_kitchen_wall_switch_battery
          - type: "custom:battery-entity"
            entity: sensor.emmas_bedroom_wall_switch_battery
          - type: "custom:battery-entity"
            entity: sensor.master_bedroom_wall_switch_battery
          - type: "custom:battery-entity"
            entity: sensor.brunos_bedside_button_battery\
          - type: "custom:battery-entity"
            entity: sensor.sarahs_bedside_button_battery
          - type: "custom:battery-entity"
            entity: sensor.dining_room_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.emmas_bedroom_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.hallway_kitchen_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.hallway_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.kitchen_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.living_room_sensor_battery
          - type: "custom:battery-entity"
            entity: sensor.master_bedroom_sensor_battery
      - type: "custom:zha-network-card"
        clickable: true
        columns:
          - name: Name
            prop: name
          - attr: available
            id: available
            modify: x || "false"
            name: Online
          - attr: manufacturer
            name: Manufacturer
          - attr: model
            name: Model
          - attr: ieee
            name: IEEE
          - name: NWK
            prop: nwk
          - attr: rssi
            name: RSSI
          - attr: lqi
            name: LQI
          - attr: last_seen
            name: Last Seen
          - attr: power_source
            name: Power Source
          - attr: quirk_class
            name: Quirk
        sort_by: available
