title: Admin
preload_cards:
  - custom:layout-card
  - layout-card
  - custom:auto-entities
  - custom:zha-network-card
  - custom:battery-entity
views:
  - path: default_view
    title: General
    cards:
      - type: "custom:auto-entities"
        id: low_battery
        show_empty: false
        card:
          title: ❗ Low Battery
          type: entities
          show_header_toggle: false
        filter:
          include:
            - domain: sensor
              entity_id: "*battery*"
              state: "<= 30"
              options:
                type: "custom:battery-entity"

  - path: zigbee
    panel: true
    title: Zigbee Mesh
    cards:
      - type: "custom:zha-network-card"
        clickable: true
        columns:
          - name: Name
            prop: name
          - attr: available
            id: available
            modify: x || "false"
            name: Online
          - attr: manufacturer
            name: Manufacturer
          - attr: model
            name: Model
          - attr: ieee
            name: IEEE
          - name: NWK
            prop: nwk
          - attr: rssi
            name: RSSI
          - attr: lqi
            name: LQI
          - attr: last_seen
            name: Last Seen
          - attr: power_source
            name: Power Source
          - attr: quirk_class
            name: Quirk
        sort_by: available
