title: Home
resources:
  - url: /local/button-card.js
    type: module
views:
  - badges: []
    cards:
      - entities:
          - switch.balcony_plug
          - light.balcony_main
        show_header_toggle: true
        title: Balcony
        type: entities
      - entities:
          - switch.dining_room_cabinet
          - light.dining_room_ceiling_kitchen
          - light.dining_room_ceiling_table
          - binary_sensor.dining_room_sensor_motion
          - sensor.dining_room_sensor_light_level
          - sensor.dining_room_sensor_temperature
        show_header_toggle: true
        title: Dining Room
        type: entities
      - entities:
          - switch.emmas_bedroom_string_lights
          - light.emmas_bedroom_ceiling
          - light.emmas_bedroom_nightlight
          - binary_sensor.emmas_bedroom_sensor_motion
          - sensor.emmas_bedroom_sensor_light_level
          - sensor.emmas_bedroom_sensor_temperature
        show_header_toggle: true
        title: Emma's Bedroom
        type: entities
      - entities:
          - sensor.hallway_sensor_light_level
          - sensor.hallway_sensor_temperature
          - binary_sensor.hallway_sensor_motion
          - light.hallway_ceiling_bathroom
          - light.hallway_ceiling_front_door
        show_header_toggle: true
        title: Hallway
        type: entities
      - entities:
          - sensor.kitchen_sensor_light_level
          - sensor.kitchen_sensor_temperature
          - binary_sensor.kitchen_sensor_motion
          - light.hue_ambiance_spot_1
          - light.kitchen_counter
          - light.hue_ambiance_spot_2
        show_header_toggle: true
        title: Kitchen
        type: entities
      - entities:
          - sensor.laundry_room_sensor_light_level
          - sensor.laundry_room_sensor_temperature
          - binary_sensor.laundry_room_sensor_motion
          - light.laundry_room_ceiling
        show_header_toggle: true
        title: Laundry Room
        type: entities
      - entities:
          - light.living_room_ceiling_desk
          - light.living_room_standing_lamp_desk
          - light.living_room_ceiling_sofa
          - light.desk_lightstrip
          - binary_sensor.living_room_sensor_motion
          - sensor.living_room_sensor_light_level
          - sensor.living_room_sensor_temperature
        show_header_toggle: true
        title: Living Room
        type: entities
      - entities:
          - light.master_bedroom_ceiling
          - binary_sensor.master_bedroom_sensor_motion
          - sensor.master_bedroom_sensor_light_level
          - sensor.master_bedroom_sensor_temperature
        show_header_toggle: true
        title: Master Bedroom
        type: entities
      - entities:
          - switch.balcony_plug
          - switch.dining_room_cabinet
          - switch.emmas_bedroom_string_lights
        show_header_toggle: true
        title: All Light Switches
        type: entities
      - entities:
          - binary_sensor.dining_room_sensor_motion
          - binary_sensor.living_room_sensor_motion
          - binary_sensor.master_bedroom_sensor_motion
          - binary_sensor.emmas_bedroom_sensor_motion
          - binary_sensor.hallway_sensor_motion
          - binary_sensor.kitchen_sensor_motion
          - binary_sensor.laundry_room_sensor_motion
        show_header_toggle: true
        title: All Motion Sensors
        type: entities
      - entities:
          - light.hue_ambiance_spot_1
          - light.hue_ambiance_spot_2
        show_header_toggle: true
        title: Light Kitchen Ceiling
        type: entities
      - entities:
          - binary_sensor.hk_presence_bruno
          - binary_sensor.hk_presence_sarah
          - binary_sensor.hk_presence_someone
        show_header_toggle: true
        title: Someone is home
        type: entities
      - entities:
          - sensor.watch_smart_tv
          - sensor.watch_netflix
          - sensor.watch_apple_tv
        show_header_toggle: false
        title: Living Room Entertainment Control
        type: entities
      - entity: alarm_control_panel.alexa_guard_a8bd5
        type: alarm-panel
      - entities:
          - automation.house_leave_house
          - automation.kitchen_motion_starts_motion_toggle_off
          - automation.living_room_motion_toggle_override_off
          - automation.house_sunrise
          - automation.kitchen_motion_ends_motion_toggle_on
          - automation.living_room_motion_toggle_override_on
          - automation.house_sunset
          - automation.emma_s_bedroom_motion_toggle_override_on
          - automation.dining_room_dining_room_motion_starts_motion_toggle_off
          - automation.hallway_motion_starts_motion_toggle_off
          - automation.house_anyone_comes_home_after_sunset
          - automation.hallway_motion_ends_motion_toggle_on
          - automation.dining_room_motion_ends_motion_toggle_on
          - automation.house_building_door_bell_ring
          - automation.laundry_room_motion_starts_motion_toggle_off
          - automation.dining_room_motion_toggle_override_off
          - automation.living_room_watch_tv_lights_on
          - automation.laundry_room_motion_ends_motion_toggle_on
          - automation.ha_set_home_assistant_theme_for_day_and_night
          - automation.dining_room_motion_toggle_override_on
          - automation.living_room_watch_tv_lights_off_daytime
          - automation.house_start_cleaning
          - automation.master_bedroom_motion_starts_motion_toggle_off
          - automation.living_room_watch_tv_lights_off_nighttime
          - automation.house_stop_cleaning
          - >-
            automation.master_bedroom_master_bedroom_motion_ends_motion_toggle_on
          - automation.living_room_watch_tv_fan_on
          - automation.house_alexa_home_guard_arm
          - automation.master_bedroom_motion_toggle_override_off
          - automation.living_room_watch_tv_fan_off
          - automation.house_alexa_home_guard_disarm
          - automation.master_bedroom_motion_toggle_override_on
          - automation.living_room_watch_tv_dnd_on
          - automation.house_sarah_comes_home
          - automation.emma_s_bedroom_motion_starts_motion_toggle_off
          - automation.living_room_watch_tv_dnd_off
          - automation.house_bruno_comes_home
          - automation.emma_s_bedroom_motion_ends_motion_toggle_on
          - automation.living_room_motion_starts_motion_toggle_off
          - automation.house_motion_presence_detected
          - automation.emma_s_bedroom_motion_toggle_override_off
          - automation.living_room_motion_ends_motion_toggle_on
          - automation.house_motion_presence_not_detected
        title: Automation
        type: entities
      - entities:
          - input_boolean.motion_living_room
          - input_boolean.motion_master_bedroom
          - input_boolean.bruno_present
          - input_boolean.motion_emmas_bedroom_room
          - input_boolean.sarah_present
          - input_boolean.motion_kitchen
          - input_boolean.someone_present
          - input_boolean.motion_hallway
          - input_boolean.motion_laundry_room
          - input_boolean.dnd_dining_room
          - input_boolean.dnd_master_bedroom
          - input_boolean.dnd_emmas_bedroom
          - input_boolean.dnd_kitchen
          - input_boolean.dnd_hallway
          - input_boolean.dnd_laundry_room
          - input_boolean.dnd_bathroom
          - input_boolean.dnd_balcony
          - input_boolean.motion_dining_room
        title: Input boolean
        type: entities
      - entities:
          - light.kitchen
          - light.dining_room
          - light.living_room
          - light.master_bedroom
          - light.balcony
          - light.laundry_room
          - light.hallway
          - light.gaming_area
          - light.emmas_bedroom
        title: Light
        type: entities
      - entities:
          - lock.home_door
          - lock.nello_ecf41382
        title: Lock
        type: entities
      - entity: media_player.living_room_tv
        type: media-control
      - entity: media_player.bruno_s_sonos_one
        type: media-control
      - entity: media_player.bathroom_echo_dot
        type: media-control
      - entity: media_player.emma_s_bedroom_echo_dot
        type: media-control
      - entity: media_player.kitchen_echo_dot
        type: media-control
      - entity: media_player.dining_room_echo_left
        type: media-control
      - entity: media_player.stereo_pair
        type: media-control
      - entity: media_player.everywhere
        type: media-control
      - entity: media_player.dining_room_echo_right
        type: media-control
      - entity: media_player.master_bedroom_echo_dot
        type: media-control
      - entities:
          - remote.harmony_hub
        title: Remote
        type: entities
      - entities:
          - script.clean_bathroom
          - script.clean_master_bedroom
          - script.emma_bedtime
          - script.clean_emmas_bedroom
          - script.good_night
          - script.start_cleaning
          - script.clean_living_room
          - script.clean_kitchen
          - script.clean_dining_room
          - script.clean_hallway
          - script.stop_cleaning
        title: Script
        type: entities
      - entities:
          - switch.homelab
        title: Switch
        type: entities
      - entities:
          - vacuum.xiaomi_vacuum_cleaner
        title: Vacuum
        type: entities
      - entity: weather.weather
        type: weather-forecast
    path: default_view
    title: Home
  - badges:
      - binary_sensor.living_room_motion_sensor
    cards:
      - entity: input_boolean.dnd_living_room
        hold_action:
          action: none
        icon: "mdi:weather-night"
        icon_height: 50px
        name: Do Not Disturb
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        theme: Backend-selected
        type: entity-button
      - entity: light.living_room
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.living_room_ceiling_sofa
          - entity: light.living_room_ceiling_desk
          - entity: light.living_room_standing_lamp_desk
        show_header_toggle: false
        title: Lights
        type: entities
      - entity: sensor.living_room_sensor_light_level
        graph: line
        name: Light Level
        theme: Backend-selected
        type: sensor
      - entity: sensor.living_room_sensor_temperature
        graph: line
        name: Temperature
        theme: Backend-selected
        type: sensor
      - entities:
          - entity: script.clean_living_room
          - entity: sensor.watch_apple_tv
          - entity: sensor.watch_netflix
          - entity: sensor.watch_smart_tv
        show_header_toggle: false
        title: Activities
        type: entities
      - entity: media_player.bruno_s_sonos_one
        type: media-control
      - - entity: input_boolean.dnd_living_room
          icon: "mdi:weather-night"
          show_state: true
          tap_action:
            action: call-service
            service: input_boolean.toggle
            service_data:
              entity_id: input_boolean.dnd_living_room
          type: "custom:button-card"
    path: living-room
    title: Living Room
  - badges:
      - binary_sensor.dining_room_motion_sensor
    cards:
      - entity: light.dining_room
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.dining_room_ceiling_kitchen
          - entity: light.dining_room_ceiling_table
          - entity: switch.dining_room_cabinet
        show_header_toggle: false
        title: Lights
        type: entities
      - detail: 10
        entity: sensor.dining_room_sensor_temperature
        graph: line
        name: Temperature
        theme: Backend-selected
        type: sensor
      - entity: sensor.dining_room_sensor_light_level
        graph: line
        name: Light Level
        theme: Backend-selected
        type: sensor
      - entity: media_player.stereo_pair
        type: media-control
    panel: false
    path: dining-room
    title: Dining Room
  - badges:
      - binary_sensor.master_bedroom_motion_sensor
    cards:
      - entity: light.master_bedroom
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.master_bedroom_ceiling
        show_header_toggle: false
        title: Lights
        type: entities
      - entity: sensor.master_bedroom_sensor_temperature
        graph: line
        name: Temperature
        theme: Backend-selected
        type: sensor
      - entity: sensor.master_bedroom_sensor_light_level
        graph: line
        name: Light Level
        theme: Backend-selected
        type: sensor
      - entity: media_player.master_bedroom_echo_dot
        type: media-control
    path: master-bedroom
    title: Master Bedroom
  - badges:
      - binary_sensor.emmas_bedroom_motion_sensor
    cards:
      - entity: light.emmas_bedroom
        name: All Lights
        type: light
      - entities:
          - entity: light.emmas_bedroom_ceiling
          - entity: light.emmas_bedroom_nightlight
          - entity: switch.emmas_bedroom_string_lights
        title: Lights
        type: entities
      - entity: sensor.emmas_bedroom_sensor_temperature
        graph: line
        name: Temperature
        theme: Backend-selected
        type: sensor
      - entity: sensor.emmas_bedroom_sensor_light_level
        graph: line
        name: Light Level
        theme: Backend-selected
        type: sensor
      - entity: media_player.emma_s_bedroom_echo_dot
        type: media-control
    path: emmas-bedroom
    title: Emma's Bedroom
  - badges:
      - binary_sensor.kitchen_motion_sensor
    cards:
      - entity: light.kitchen
        name: All Lights
        type: light
      - entities:
          - entity: light.kitchen_counter
          - entity: light.hue_ambiance_spot_1
          - entity: light.hue_ambiance_spot_2
        show_header_toggle: false
        title: Lights
        type: entities
      - entity: sensor.kitchen_sensor_temperature
        graph: line
        name: Temperature
        theme: Backend-selected
        type: sensor
      - entity: sensor.kitchen_sensor_light_level
        graph: line
        name: Light Level
        theme: Backend-selected
        type: sensor
      - entity: media_player.kitchen_echo_dot
        type: media-control
    path: kitchen
    title: Kitchen
  - badges:
      - binary_sensor.hallway_motion_sensor
    cards:
      - entity: light.hallway
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.hallway_ceiling_bathroom
          - entity: light.hallway_ceiling_front_door
        show_header_toggle: false
        title: All Lights
        type: entities
      - entity: sensor.hallway_sensor_temperature
        graph: line
        name: Temperature
        theme: Backend-selected
        type: sensor
      - entity: sensor.hallway_sensor_light_level
        graph: line
        name: Light Level
        theme: Backend-selected
        type: sensor
    path: hallway
    title: Hallway
  - badges:
      - binary_sensor.laundry_room_motion_sensor
    cards:
      - entity: light.laundry_room
        name: Light
        theme: Backend-selected
        type: light
    path: laundry-room
    title: Laundry Room
