title: Home
resources:
  - url: /local/community/button-card/button-card.js?v=1
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
views:
  - cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - entity: input_boolean.dnd_house
                icon: "mdi:weather-night"
                show_state: false
                name: Do Not Disturb
                size: 25%
                tap_action:
                  action: call-service
                  service: input_boolean.toggle
                  service_data:
                    entity_id: group.dnd_house
                type: "custom:button-card"
              - entity: script.start_cleaning
                icon: "mdi:broom"
                show_state: false
                name: Clean House
                size: 25%
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.start_cleaning
                type: "custom:button-card"
              - entity: script.stop_cleaning
                icon: "mdi:cancel"
                show_state: false
                name: Stop Cleaning
                size: 25%
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.stop_cleaning
                type: "custom:button-card"
      - entity: weather.weather
        type: "custom:weather-card"
      - entities:
          - entity: sensor.home_sensor_average_temperature
            name: Avg. Temperature
          - entity: sensor.home_sensor_average_light_level
            name: Avg. Light Level
        type: "custom:mini-graph-card"
        icon: "mdi:thermometer"
      - type: entity-filter
        entities:
          - input_boolean.bruno_present
          - input_boolean.sarah_present
        state_filter:
          - "on"
        card:
          type: glance
          title: Who's Home
          show_state: false
      - entity: alarm_control_panel.alexa_guard_a8bd5
        type: alarm-panel
      - entities:
          - light.kitchen
          - light.dining_room
          - light.living_room
          - light.master_bedroom
          - light.balcony
          - light.laundry_room
          - light.hallway
          - light.gaming_area
          - light.emmas_bedroom
        title: Lights
        type: entities
      - entities:
          - lock.home_door
          - lock.nello_ecf41382
        title: Doors
        show_header_toggle: false
        type: entities
      - entity: media_player.everywhere
        type: media-control
      - type: "custom:xiaomi-vacuum-card"
        entity: vacuum.xiaomi_vacuum_cleaner
        image: false
        name: Robot Vacuum
    path: default_view
    title: House
  - cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - entity: input_boolean.dnd_living_room
                icon: "mdi:weather-night"
                show_state: false
                name: Do Not Disturb
                size: 25%
                tap_action:
                  action: call-service
                  service: input_boolean.toggle
                  service_data:
                    entity_id: input_boolean.dnd_living_room
                type: "custom:button-card"
              - entity: script.clean_living_room
                icon: "mdi:broom"
                show_state: false
                name: Clean
                size: 25%
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.clean_living_room
                type: "custom:button-card"
              - entity: script.stop_cleaning
                icon: "mdi:cancel"
                show_state: false
                name: Stop Cleaning
                size: 25%
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.stop_cleaning
                type: "custom:button-card"
          - type: horizontal-stack
            cards:
              - entity: sensor.watch_smart_tv
                icon: "mdi:television"
                show_state: false
                name: Watch TV
                size: 25%
                tap_action:
                  action: call-service
                  service: remote.turn_on
                  service_data:
                    entity_id: remote.harmony_hub
                    activity: "Watch Smart TV"
                type: "custom:button-card"
              - entity: sensor.watch_netflix
                icon: "mdi:netflix"
                show_state: false
                name: Watch Netflix
                size: 25%
                tap_action:
                  action: call-service
                  service: remote.turn_on
                  service_data:
                    entity_id: remote.harmony_hub
                    activity: "Watch Netflix"
                type: "custom:button-card"
              - entity: sensor.watch_apple_tv
                icon: "mdi:apple"
                show_state: false
                name: Watch Cartoons
                size: 25%
                tap_action:
                  action: call-service
                  service: remote.turn_on
                  service_data:
                    entity_id: remote.harmony_hub
                    activity: "Watch Apple TV"
                type: "custom:button-card"
      - entity: light.living_room
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.living_room_ceiling_sofa
          - entity: light.living_room_ceiling_desk
          - entity: light.living_room_standing_lamp_desk
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - entity: sensor.living_room_sensor_temperature
            name: Temperature
          - entity: sensor.living_room_sensor_light_level
            name: Light Level
        type: "custom:mini-graph-card"
      - entity: media_player.bruno_s_sonos_one
        type: media-control
    path: living-room
    title: Living Room
  - cards:
      - type: horizontal-stack
        cards:
          - entity: input_boolean.dnd_dining_room
            icon: "mdi:weather-night"
            show_state: false
            name: Do Not Disturb
            size: 25%
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.dnd_dining_room
            type: "custom:button-card"
          - entity: script.clean_dining_room
            icon: "mdi:broom"
            show_state: false
            name: Clean
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.clean_dining_room
            type: "custom:button-card"
          - entity: script.stop_cleaning
            icon: "mdi:cancel"
            show_state: false
            name: Stop Cleaning
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.stop_cleaning
            type: "custom:button-card"
      - entity: light.dining_room
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.dining_room_ceiling_kitchen
          - entity: light.dining_room_ceiling_table
          - entity: switch.dining_room_cabinet
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - entity: sensor.dining_room_sensor_temperature
            name: Temperature
          - entity: sensor.dining_room_sensor_light_level
            name: Light Level
        type: "custom:mini-graph-card"
      - entity: media_player.stereo_pair
        type: media-control
    panel: false
    path: dining-room
    title: Dining Room
  - cards:
      - type: horizontal-stack
        cards:
          - entity: input_boolean.dnd_master_bedroom
            icon: "mdi:weather-night"
            show_state: false
            name: Do Not Disturb
            size: 25%
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.dnd_master_bedroom
            type: "custom:button-card"
          - entity: script.clean_master_bedroom
            icon: "mdi:broom"
            show_state: false
            name: Clean
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.clean_master_bedroom
            type: "custom:button-card"
          - entity: script.stop_cleaning
            icon: "mdi:cancel"
            show_state: false
            name: Stop Cleaning
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.stop_cleaning
            type: "custom:button-card"
      - entity: light.master_bedroom
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.master_bedroom_ceiling
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - entity: sensor.master_bedroom_sensor_temperature
            name: Temperature
          - entity: sensor.master_bedroom_sensor_light_level
            name: Light Level
        type: "custom:mini-graph-card"
      - entity: media_player.master_bedroom_echo_dot
        type: media-control
    path: master-bedroom
    title: Master Bedroom
  - cards:
      - type: horizontal-stack
        cards:
          - entity: input_boolean.dnd_emmas_bedroom
            icon: "mdi:weather-night"
            show_state: false
            name: Do Not Disturb
            size: 25%
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.dnd_emmas_bedroom
            type: "custom:button-card"
          - entity: script.clean_emmas_bedroom
            icon: "mdi:broom"
            show_state: false
            name: Clean
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.clean_emmas_bedroom
            type: "custom:button-card"
          - entity: script.stop_cleaning
            icon: "mdi:cancel"
            show_state: false
            name: Stop Cleaning
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.stop_cleaning
            type: "custom:button-card"
      - entity: light.emmas_bedroom
        name: All Lights
        type: light
      - entities:
          - entity: light.emmas_bedroom_ceiling
          - entity: light.emmas_bedroom_nightlight
          - entity: switch.emmas_bedroom_string_lights
        title: Lights
        type: entities
      - entities:
          - entity: sensor.emmas_bedroom_sensor_temperature
            name: Temperature
          - entity: sensor.emmas_bedroom_sensor_light_level
            name: Light Level
        type: "custom:mini-graph-card"
      - entity: media_player.emma_s_bedroom_echo_dot
        type: media-control
    path: emmas-bedroom
    title: Emma's Bedroom
  - cards:
      - type: horizontal-stack
        cards:
          - entity: input_boolean.dnd_kitchen
            icon: "mdi:weather-night"
            show_state: false
            name: Do Not Disturb
            size: 25%
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.dnd_kitchen
            type: "custom:button-card"
          - entity: script.clean_kitchen
            icon: "mdi:broom"
            show_state: false
            name: Clean
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.clean_kitchen
            type: "custom:button-card"
          - entity: script.stop_cleaning
            icon: "mdi:cancel"
            show_state: false
            name: Stop Cleaning
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.stop_cleaning
            type: "custom:button-card"
      - entity: light.kitchen
        name: All Lights
        type: light
      - entities:
          - entity: light.kitchen_counter
          - entity: light.hue_ambiance_spot_1
          - entity: light.hue_ambiance_spot_2
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - entity: sensor.kitchen_sensor_temperature
            name: Temperature
          - entity: sensor.kitchen_sensor_light_level
            name: Light Level
        type: "custom:mini-graph-card"
      - entity: media_player.kitchen_echo_dot
        type: media-control
    path: kitchen
    title: Kitchen
  - cards:
      - type: horizontal-stack
        cards:
          - entity: input_boolean.dnd_hallway
            icon: "mdi:weather-night"
            show_state: false
            name: Do Not Disturb
            size: 25%
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.dnd_hallway
            type: "custom:button-card"
          - entity: script.clean_hallway
            icon: "mdi:broom"
            show_state: false
            name: Clean
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.clean_hallway
            type: "custom:button-card"
          - entity: script.stop_cleaning
            icon: "mdi:cancel"
            show_state: false
            name: Stop Cleaning
            size: 25%
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.stop_cleaning
            type: "custom:button-card"
      - entity: light.hallway
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.hallway_ceiling_bathroom
          - entity: light.hallway_ceiling_front_door
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - entity: sensor.hallway_sensor_temperature
            name: Temperature
          - entity: sensor.hallway_sensor_light_level
            name: Light Level
        type: "custom:mini-graph-card"
    path: hallway
    title: Hallway
  - cards:
      - entity: light.balcony
        name: All Lights
        theme: Backend-selected
        type: light
      - entities:
          - entity: light.balcony_main
          - entity: switch.balcony_plug
        show_header_toggle: false
        title: Lights
        type: entities
    path: balcony
    title: Balcony
  - cards:
      - entity: light.laundry_room
        name: Light
        theme: Backend-selected
        type: light
      - entities:
          - entity: sensor.laundry_room_sensor_temperature
            name: Temperature
          - entity: sensor.laundry_room_sensor_light_level
            name: Light Level
        type: "custom:mini-graph-card"
    path: laundry-room
    title: Laundry Room
