- platform: template
  sensors:
    hallway_light_level:
      friendly_name: 'Hallway Light Level'
      value_template: '{{states.sensor.hallway_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux

    laundry_room_light_level:
      friendly_name: 'Laundry Room Light Level'
      value_template: '{{states.sensor.laundry_room_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux
