- platform: template
  sensors:
    hallway_temperature:
      friendly_name: 'Hallway Temperature'
      value_template: '{{states.sensor.hallway_motion_sensor.attributes.temperature}}'
      unit_of_measurement: °C
      device_class: temperature

    laundry_room_temperature:
      friendly_name: 'Laundry Room Temperature'
      value_template: '{{states.sensor.laundry_room_motion_sensor.attributes.temperature}}'
      unit_of_measurement: °C
      device_class: temperature
