binary_sensor:
  - platform: huesensor

  - platform: template
    sensors:
      hk_dining_room_sensor_motion:
        friendly_name: Motion Sensor Dining Room
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.hk_motion_sensor_dining_room', 'on') }}
      hk_living_room_sensor_motion:
        friendly_name: Motion Sensor Living Room
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.hk_motion_sensor_living_room', 'on') }}
      hk_master_bedroom_sensor_motion:
        friendly_name: Motion Sensor Master Bedroom
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.hk_motion_sensor_master_bedroom', 'on') }}
      hk_emmas_bedroom_sensor_motion:
        friendly_name: Motion Sensor Emma's Bedroom
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.hk_motion_sensor_emmas_bedroom', 'on') }}
      hk_kitchen_sensor_motion:
        friendly_name: Motion Sensor Kitchen
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.hk_motion_sensor_kitchen', 'on') }}
      hk_hallway_sensor_motion:
        friendly_name: Motion Sensor Hallway
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.hk_motion_sensor_hallway', 'on') }}
      hk_hallway_kitchen_sensor_motion:
        friendly_name: Motion Sensor Hallway Kitchen
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.hk_motion_sensor_hallway_kitchen', 'on') }}
      hallway_combined_sensor_motion:
        friendly_name: Motion Sensor Hallway Combined
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.hk_hallway_kitchen_sensor_motion', 'on') or is_state('binary_sensor.hk_hallway_sensor_motion', 'on') }}

      hk_presence_bruno:
        friendly_name: "Presence Bruno"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.bruno_present', 'on') }}
      hk_presence_sarah:
        friendly_name: "Presence Sarah"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.sarah_present', 'on') }}
      hk_presence_someone:
        friendly_name: "Presence Someone"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.someone_present', 'on') }}
      someone_home:
        device_class: presence
        friendly_name: Someone is home
        value_template: >-
          {{ is_state('group.presence', 'on') }}

      presence_living_room:
        friendly_name: Presence Living Room
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_living_room', 'on') }}

      presence_dining_room:
        friendly_name: Presence Dining Room
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_dining_room', 'on') }}

      presence_master_bedroom:
        friendly_name: Presence Master Bedroom
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_master_bedroom', 'on') }}

      presence_emmas_bedroom:
        friendly_name: Presence Emma's Bedroom
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_emmas_bedroom', 'on') }}

      presence_kitchen:
        friendly_name: Presence Kitchen
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_kitchen', 'on') }}

      presence_hallway:
        friendly_name: Presence Hallway
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_hallway', 'on') }}

      presence_laundry_room:
        friendly_name: Presence Laundry Room
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_laundry_room', 'on') }}

      presence_balcony:
        friendly_name: Presence Balcony
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_balcony', 'on') }}
