binary_sensor:
  - platform: huesensor

  - platform: template
    sensors:
      hk_presence_bruno:
        friendly_name: "Presence Bruno"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.bruno_present', 'on') }}
  - platform: template
    sensors:
      hk_presence_sarah:
        friendly_name: "Presence Sarah"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.sarah_present', 'on') }}
  - platform: template
    sensors:
      someone_home:
        device_class: presence
        friendly_name: Someone is home
        entity_id:
          - binary_sensor.hk_presence_bruno
          - binary_sensor.hk_presence_sarah
        value_template: >-
          {{ is_state('binary_sensor.hk_presence_bruno', 'on') or is_state('binary_sensor.hk_presence_sarah', 'on') }}

input_boolean:
  bruno_present:
    name: bruno
    icon: mdi:account
  sarah_present:
    name: sarah
    icon: mdi:account
