binary_sensor:
  - platform: huesensor

  - platform: template
    sensors:
      hallway_combined_sensor_motion:
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.hallway_kitchen_sensor_motion', 'on') or is_state('binary_sensor.hallway_sensor_motion', 'on') }}
      hk_presence_bruno:
        friendly_name: "Presence Bruno"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.bruno_present', 'on') }}
      hk_presence_sarah:
        friendly_name: "Presence Sarah"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.sarah_present', 'on') }}
      hk_presence_someone:
        friendly_name: "Presence Someone"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.someone_present', 'on') }}
      someone_home:
        device_class: presence
        friendly_name: Someone is home
        value_template: >-
          {{ is_state('group.presence', 'on') }}
