binary_sensor:
  - platform: template
    sensors:
      presence_bruno:
        friendly_name: "Presence Bruno"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_bruno', 'on') }}
      presence_sarah:
        friendly_name: "Presence Sarah"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_sarah', 'on') }}
      presence_someone:
        friendly_name: "Presence Someone"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_someone', 'on') }}
      someone_home:
        device_class: presence
        friendly_name: Someone is home
        value_template: >-
          {{ is_state('group.presence', 'on') }}

      presence_living_room:
        friendly_name: Presence Living Room
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_living_room_motion', 'on')  or is_state('input_boolean.presence_living_room_switch', 'on') or is_state('input_boolean.presence_living_room_tv', 'on') or is_state('input_boolean.presence_living_room_assistant', 'on')}}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_living_room.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}

      presence_master_bedroom:
        friendly_name: Presence Master Bedroom
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_master_bedroom_motion', 'on') or is_state('input_boolean.presence_master_bedroom_switch', 'on') or is_state('input_boolean.presence_master_bedroom_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_master_bedroom.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_emmas_bedroom:
        friendly_name: Presence Emma's Bedroom
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_emmas_bedroom_motion', 'on') or is_state('input_boolean.presence_emmas_bedroom_switch', 'on') or is_state('input_boolean.presence_emmas_bedroom_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_emmas_bedroom.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_kitchen:
        friendly_name: Presence Kitchen
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_kitchen_motion', 'on') or is_state('input_boolean.presence_kitchen_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_kitchen.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_hallway_ground_floor:
        friendly_name: Presence Hallway Ground Floor
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_hallway_ground_floor_motion', 'on') or is_state('input_boolean.presence_hallway_ground_floor_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_hallway_ground_floor.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_hallway_1st_floor:
        friendly_name: Presence Hallway 1st Floor
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_hallway_1st_floor_motion', 'on') or is_state('input_boolean.presence_hallway_1st_floor_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_hallway_1st_floor.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_hallway_1st_floor_stairs:
        friendly_name: Presence Hallway 1st Floor Stairs
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_hallway_1st_floor_stairs_motion', 'on') or is_state('input_boolean.presence_hallway_1st_floor_stairs_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_hallway_1st_floor_stairs.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_hallway_2nd_floor:
        friendly_name: Presence Hallway 2nd Floor
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_hallway_2nd_floor_motion', 'on') or is_state('input_boolean.presence_hallway_2nd_floor_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_hallway_2nd_floor.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_hallway_2nd_floor_stairs:
        friendly_name: Presence Hallway 2nd Floor Stairs
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_hallway_2nd_floor_stairs_motion', 'on') or is_state('input_boolean.presence_hallway_2nd_floor_stairs_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_hallway_2nd_floor_stairs.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_bathroom_1st_floor:
        friendly_name: Presence Bathroom 1st Floor
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_bathroom_1st_floor_switch', 'on') or is_state('input_boolean.presence_bathroom_1st_floor_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_bathroom_1st_floor.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_office:
        friendly_name: Presence Office
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_office_motion', 'on') or is_state('input_boolean.presence_office_switch', 'on') or is_state('input_boolean.presence_office_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_office.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_hobby_room:
        friendly_name: Presence Hobby Room
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_hobby_room_motion', 'on') or is_state('input_boolean.presence_hobby_room_switch', 'on') or is_state('input_boolean.presence_hobby_room_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_hobby_room.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_garden:
        friendly_name: Presence Garden
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.presence_garden_motion', 'on') or is_state('input_boolean.presence_garden_assistant', 'on') }}
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_garden.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
