sensor:
  - platform: min_max
    name: hallway_sensor_average_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_ground_floor_sensor_light_level
      - sensor.hallway_1st_floor_sensor_light_level
      - sensor.hallway_2nd_floor_sensor_light_level

  - platform: min_max
    name: hallway_sensor_average_temperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_ground_floor_sensor_temperature
      - sensor.hallway_1st_floor_sensor_temperature
      - sensor.hallway_2nd_floor_sensor_temperature

  - platform: min_max
    name: home_sensor_average_temperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_ground_floor_sensor_temperature
      - sensor.hallway_1st_floor_sensor_temperature
      - sensor.hallway_2nd_floor_sensor_temperature
      - sensor.kitchen_sensor_temperature
      - sensor.living_room_sensor_temperature
      - sensor.master_bedroom_sensor_temperature
      - sensor.emmas_bedroom_sensor_temperature
      - sensor.office_sensor_temperature

  - platform: min_max
    name: home_sensor_average_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_ground_floor_sensor_light_level
      - sensor.hallway_1st_floor_sensor_light_level
      - sensor.hallway_2nd_floor_sensor_light_level
      - sensor.kitchen_sensor_light_level
      - sensor.living_room_sensor_light_level
      - sensor.master_bedroom_sensor_light_level
      - sensor.emmas_bedroom_sensor_light_level
      - sensor.office_sensor_light_level

  - platform: min_max
    name: hallway_combined_sensor_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_ground_floor_sensor_light_level
      - sensor.hallway_1st_floor_sensor_light_level
      - sensor.hallway_2nd_floor_sensor_light_level
