sensor:
  - platform: google_wifi

  - platform: huesensor

  - platform: min_max
    name: hallway_sensor_average_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_sensor_light_level
      - sensor.hallway_kitchen_sensor_light_level

  - platform: min_max
    name: hallway_sensor_average_temperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_sensor_temperature
      - sensor.hallway_kitchen_sensor_temperature

  - platform: min_max
    name: home_sensor_average_temperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_sensor_temperature
      - sensor.hallway_kitchen_sensor_temperature
      - sensor.kitchen_sensor_temperature
      - sensor.living_room_sensor_temperature
      - sensor.dining_room_sensor_temperature
      - sensor.master_bedroom_sensor_temperature
      - sensor.emmas_bedroom_sensor_temperature

  - platform: min_max
    name: home_sensor_average_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_sensor_light_level
      - sensor.hallway_kitchen_sensor_light_level
      - sensor.kitchen_sensor_light_level
      - sensor.living_room_sensor_light_level
      - sensor.dining_room_sensor_light_level
      - sensor.master_bedroom_sensor_light_level
      - sensor.emmas_bedroom_sensor_light_level

  - platform: template
    sensors:
      watch_netflix:
        friendly_name: Watch Netflix
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Netflix') }}"
      watch_smart_tv:
        friendly_name: Watch Smart TV
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Smart TV') }}"
      watch_apple_tv:
        friendly_name: Watch Apple TV
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Apple TV') }}"
      listen_music:
        friendly_name: Listen to Music
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Music') }}"

  - platform: template
    sensors:
      homelab_amps:
        value_template: '{{ states.switch.homelab.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: "A"
      homelab_watts:
        value_template: '{{ states.switch.homelab.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: "W"
      homelab_total_kw:
        value_template: '{{ states.switch.homelab.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: "kW"
      homelab_volts:
        value_template: '{{ states.switch.homelab.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: "V"
      homelab_today_kw:
        value_template: '{{ states.switch.homelab.attributes["today_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: "kW"

  - platform: template
    sensors:
      house_alarm_clock_time:
        friendly_name: "Alarm Time"
        value_template: "{{ states.input_number.house_alarm_clock_hour.state | int }}:{% if states.input_number.house_alarm_clock_minutes.state | int < 10 %}0{% endif %}{{ states.input_number.house_alarm_clock_minutes.state | int }}"

  - platform: min_max
    name: hallway_combined_sensor_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_sensor_light_level
      - sensor.hallway_kitchen_sensor_light_level
