sensor:
  - platform: template
    sensors:
      hallway_light_level:
        friendly_name: "Hallway Light Level"
        value_template: "{{states.sensor.hallway_motion_sensor.attributes.lx}}"
        unit_of_measurement: lux

      laundry_room_light_level:
        friendly_name: "Laundry Room Light Level"
        value_template: "{{states.sensor.laundry_room_motion_sensor.attributes.lx}}"
        unit_of_measurement: lux

      kitchen_light_level:
        friendly_name: "Kitchen Light Level"
        value_template: "{{states.sensor.kitchen_motion_sensor.attributes.lx}}"
        unit_of_measurement: lux

  - platform: template
    sensors:
      hallway_temperature:
        friendly_name: "Hallway Temperature"
        value_template: "{{states.sensor.hallway_motion_sensor.attributes.temperature}}"
        unit_of_measurement: 째C
        device_class: temperature

      laundry_room_temperature:
        friendly_name: "Laundry Room Temperature"
        value_template: "{{states.sensor.laundry_room_motion_sensor.attributes.temperature}}"
        unit_of_measurement: 째C
        device_class: temperature

      kitchen_temperature:
        friendly_name: "Kitchen Temperature"
        value_template: "{{states.sensor.kitchen_motion_sensor.attributes.temperature}}"
        unit_of_measurement: 째C
        device_class: temperature

  - platform: min_max
    name: temperature_average_home
    type: mean
    round_digits: 1
    unit_of_measurement: 째C
    device_class: temperature
    entity_ids:
      - sensor.hallway_temperature
      - sensor.laundry_room_temperature
      - sensor.kitchen_temperature

binary_sensor:
  - platform: template
    sensors:
      hallway_motion:
        friendly_name: "Hallway Motion"
        value_template: "{{states.sensor.hallway_motion_sensor.state == 'on'}}"
        device_class: motion

      laundry_room_motion:
        friendly_name: "Laundry Room Motion"
        value_template: "{{states.sensor.laundry_room_motion_sensor.state == 'on'}}"
        device_class: motion

      kitchen_motion:
        friendly_name: "Kitchen Motion"
        value_template: "{{states.sensor.kitchen_motion_sensor.state == 'on'}}"
        device_class: motion
