sensor:
  - platform: min_max
    name: temperature_average_home
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_sensor_temperature
      - sensor.laundry_sensor_room_temperature
      - sensor.kitchen_sensor_temperature
