sensor:
  - platform: google_wifi

  - platform: min_max
    name: temperature_average_home
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hallway_sensor_temperature
      - sensor.laundry_sensor_room_temperature
      - sensor.kitchen_sensor_temperature
      - sensor.living_room_sensor_temperature
      - sensor.dining_room_sensor_temperature

  - platform: template
    sensors:
      homelab_amps:
        value_template: '{{ states.switch.homelab.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: 'A'
      homelab_watts:
        value_template: '{{ states.switch.homelab.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
      homelab_total_kw:
        value_template: '{{ states.switch.homelab.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'
      homelab_volts:
        value_template: '{{ states.switch.homelab.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: 'V'
      homelab_today_kw:
        value_template: '{{ states.switch.homelab.attributes["today_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'

binary_sensor:
  - platform: template
    sensors:
      someone_home:
        device_class: presence
        friendly_name: Someone is home
        entity_id:
        - binary_sensor.hk_presence_bruno
        - binary_sensor.hk_presence_sarah
        value_template: >-
          {{ is_state('binary_sensor.hk_presence_bruno', 'on') or is_state('binary_sensor.hk_presence_sarah', 'on') }}
