sensor:
  - platform: google_wifi

  - platform: min_max
    name: hallway_sensor_average_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.zha_hallway_sensor_light_level
      - sensor.zha_hallway_kitchen_sensor_light_level

  - platform: min_max
    name: hallway_sensor_average_temperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.zha_hallway_sensor_temperature
      - sensor.zha_hallway_kitchen_sensor_temperature

  - platform: min_max
    name: home_sensor_average_temperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.zha_hallway_sensor_temperature
      - sensor.zha_hallway_kitchen_sensor_temperature
      - sensor.zha_kitchen_sensor_temperature
      - sensor.zha_living_room_sensor_temperature
      - sensor.zha_dining_room_sensor_temperature
      - sensor.zha_master_bedroom_sensor_temperature
      - sensor.zha_emmas_bedroom_sensor_temperature

  - platform: min_max
    name: home_sensor_average_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.zha_hallway_sensor_light_level
      - sensor.zha_hallway_kitchen_sensor_light_level
      - sensor.zha_kitchen_sensor_light_level
      - sensor.zha_living_room_sensor_light_level
      - sensor.zha_dining_room_sensor_light_level
      - sensor.zha_master_bedroom_sensor_light_level
      - sensor.zha_emmas_bedroom_sensor_light_level

  - platform: template
    sensors:
      watch_netflix:
        friendly_name: Watch Netflix
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Netflix') }}"
      watch_tv:
        friendly_name: Watch TV
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
      watch_cartoons:
        friendly_name: Watch Cartoons
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Cartoons') }}"
      listen_music:
        friendly_name: Listen to Music
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Music') }}"
      tv_activity:
        friendly_name: TV Activity
        value_template: "{{ is_state('sensor.watch_netflix', 'True') or is_state('sensor.watch_tv', 'True') or is_state('sensor.watch_cartoons', 'True') or is_state('sensor.listen_music', 'True') }}"

  - platform: template
    sensors:
      homelab_amps:
        value_template: '{{ states.switch.homelab.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: "A"
      homelab_watts:
        value_template: '{{ states.switch.homelab.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: "W"
      homelab_total_kw:
        value_template: '{{ states.switch.homelab.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: "kW"
      homelab_volts:
        value_template: '{{ states.switch.homelab.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: "V"
      homelab_today_kw:
        value_template: '{{ states.switch.homelab.attributes["today_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: "kW"

  - platform: min_max
    name: hallway_combined_sensor_light_level
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.zha_hallway_sensor_light_level
      - sensor.zha_hallway_kitchen_sensor_light_level
