- platform: template
  switches:
    watch_netflix:
      friendly_name: Watch Netflix
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Netflix') }}"
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.start_watch_netflix
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.stop_watch_netflix
